tests: preprocess -expected.gir files
On win32 we get shared-library="something.dll" instead
of shared-library="something.so". Preprocess the -expected.gir
files so @SHLIB_SUFFIX@ gets substituted with the value
detected at configure time.

https://bugzilla.gnome.org/show_bug.cgi?id=745636

diff --git a/tests/gi-tester b/tests/gi-tester
--- a/tests/gi-tester
+++ b/tests/gi-tester
@@ -11,8 +11,18 @@ case $targetname in
 *.gir)
     len=${#targetname}
     limit=$(expr $len - 4)
-    diff -u -U 10 ${srcdir}/${targetname:0:${limit}}-expected.gir ${builddir}/${targetname}
-    exit $?
+    expectedname=${targetname:0:${limit}}-expected.gir
+
+    if [[ -e "${srcdir}/${expectedname}" ]]; then
+        diff -u -U 10 ${srcdir}/${expectedname} ${builddir}/${targetname}
+        exit $?
+    elif [[ -e "${builddir}/${expectedname}" ]]; then
+        diff -u -U 10 ${builddir}/${expectedname} ${builddir}/${targetname}
+        exit $?
+    else
+        echo \"${expectedname}\" not found in \"${srcdir}\" or \"${builddir}\" >&2
+        exit 1
+    fi
     ;;
 *.typelib)
     # Do nothing for typelibs, this just ensures they build as part of the tests
